// <auto-generated />
using System;
using ExtraTime.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtraTime.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260217081314_AddMlBotEntities")]
    partial class AddMlBotEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExtraTime.Domain.Entities.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobType");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.ToTable("BackgroundJobs", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PredictedAwayScore")
                        .HasColumnType("int");

                    b.Property<int>("PredictedHomeScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("LeagueId", "MatchId");

                    b.HasIndex("UserId", "LeagueId");

                    b.HasIndex("LeagueId", "UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("Bets", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.BetResult", b =>
                {
                    b.Property<Guid>("BetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrectResult")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExactMatch")
                        .HasColumnType("bit");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.HasKey("BetId");

                    b.ToTable("BetResults", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Configuration")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastBetPlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Bots", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.BotPredictionAccuracy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPointsPerBet")
                        .HasColumnType("float");

                    b.Property<double>("AwayScoreMAE")
                        .HasColumnType("float");

                    b.Property<int>("BetsLost")
                        .HasColumnType("int");

                    b.Property<int>("BetsWon")
                        .HasColumnType("int");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalculationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("CorrectResultAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("CorrectResults")
                        .HasColumnType("int");

                    b.Property<double>("ExactScoreAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("ExactScores")
                        .HasColumnType("int");

                    b.Property<int>("GoalsOffBy1")
                        .HasColumnType("int");

                    b.Property<int>("GoalsOffBy2")
                        .HasColumnType("int");

                    b.Property<int>("GoalsOffBy3Plus")
                        .HasColumnType("int");

                    b.Property<double>("HomeScoreMAE")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("MeanAbsoluteError")
                        .HasColumnType("float");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("RootMeanSquaredError")
                        .HasColumnType("float");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TotalPointsEarned")
                        .HasColumnType("float");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("int");

                    b.Property<double>("Within1GoalAccuracy")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BotId", "PeriodType", "PeriodStart")
                        .HasDatabaseName("IX_BotPredictionAccuracies_BotId_PeriodType_PeriodStart");

                    b.ToTable("BotPredictionAccuracies", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CurrentMatchday")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CurrentSeasonEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentSeasonStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("League");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Competitions", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.CompetitionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("CompetitionId", "TeamId", "Season")
                        .IsUnique();

                    b.ToTable("CompetitionTeams", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.FootballStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Lost")
                        .HasColumnType("int");

                    b.Property<int>("PlayedGames")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Won")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "Type", "Position");

                    b.HasIndex("SeasonId", "TeamId", "Type", "Stage", "Group")
                        .IsUnique()
                        .HasFilter("[Stage] IS NOT NULL AND [Group] IS NOT NULL");

                    b.ToTable("FootballStandings", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.HeadToHead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BothTeamsScoredCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastMatchDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastMatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MatchesAnalyzed")
                        .HasColumnType("int");

                    b.Property<int>("Over25Count")
                        .HasColumnType("int");

                    b.Property<int>("RecentDraws")
                        .HasColumnType("int");

                    b.Property<int>("RecentMatchesCount")
                        .HasColumnType("int");

                    b.Property<int>("RecentTeam1Wins")
                        .HasColumnType("int");

                    b.Property<int>("RecentTeam2Wins")
                        .HasColumnType("int");

                    b.Property<int>("Team1Goals")
                        .HasColumnType("int");

                    b.Property<int>("Team1HomeConceded")
                        .HasColumnType("int");

                    b.Property<int>("Team1HomeGoals")
                        .HasColumnType("int");

                    b.Property<int>("Team1HomeMatches")
                        .HasColumnType("int");

                    b.Property<int>("Team1HomeWins")
                        .HasColumnType("int");

                    b.Property<Guid>("Team1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Team1Wins")
                        .HasColumnType("int");

                    b.Property<int>("Team2Goals")
                        .HasColumnType("int");

                    b.Property<Guid>("Team2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Team2Wins")
                        .HasColumnType("int");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("Team2Id");

                    b.HasIndex("Team1Id", "Team2Id", "CompetitionId")
                        .IsUnique();

                    b.ToTable("HeadToHeads", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.IntegrationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("AverageSyncDuration")
                        .HasColumnType("time");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFreshAsOf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisabledBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IntegrationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsManuallyDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAttemptedSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastErrorDetails")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastFailedSync")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSuccessfulSync")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StaleThreshold")
                        .HasColumnType("time");

                    b.Property<int>("SuccessfulSyncs24h")
                        .HasColumnType("int");

                    b.Property<int>("TotalFailures24h")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationName")
                        .IsUnique();

                    b.ToTable("IntegrationStatuses", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedCompetitionIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BettingDeadlineMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("BotsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("InviteCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoreCorrectResult")
                        .HasColumnType("int");

                    b.Property<int>("ScoreExactMatch")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.LeagueBotMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("LeagueId", "BotId")
                        .IsUnique();

                    b.ToTable("LeagueBotMembers", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique();

                    b.ToTable("LeagueMembers", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.LeagueStanding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BestStreak")
                        .HasColumnType("int");

                    b.Property<int>("BetsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("CorrectResults")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("ExactMatches")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique();

                    b.HasIndex("LeagueId", "TotalPoints", "ExactMatches", "BetsPlaced", "UserId");

                    b.ToTable("LeagueStandings", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayHalfTimeScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HomeHalfTimeScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MatchDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Matchday")
                        .HasColumnType("int");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("MatchDateUtc");

                    b.HasIndex("SeasonId");

                    b.HasIndex("Status");

                    b.HasIndex("MatchDateUtc", "Status");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchLineup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bench")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("CaptainName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CoachName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Formation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StartingXi")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchId", "TeamId")
                        .IsUnique();

                    b.ToTable("MatchLineups", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchOdds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AwayWinOdds")
                        .HasColumnType("float");

                    b.Property<double>("AwayWinProbability")
                        .HasColumnType("float");

                    b.Property<double?>("BttsNoOdds")
                        .HasColumnType("float");

                    b.Property<double?>("BttsYesOdds")
                        .HasColumnType("float");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("DrawOdds")
                        .HasColumnType("float");

                    b.Property<double>("DrawProbability")
                        .HasColumnType("float");

                    b.Property<double>("FavoriteConfidence")
                        .HasColumnType("float");

                    b.Property<double>("HomeWinOdds")
                        .HasColumnType("float");

                    b.Property<double>("HomeWinProbability")
                        .HasColumnType("float");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MarketFavorite")
                        .HasColumnType("int");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Over25Odds")
                        .HasColumnType("float");

                    b.Property<double?>("Under25Odds")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchOdds", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<int?>("AwayFouls")
                        .HasColumnType("int");

                    b.Property<int?>("AwayHalfTimeGoals")
                        .HasColumnType("int");

                    b.Property<int?>("AwayRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShots")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayYellowCards")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<int?>("HomeFouls")
                        .HasColumnType("int");

                    b.Property<int?>("HomeHalfTimeGoals")
                        .HasColumnType("int");

                    b.Property<int?>("HomeRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShots")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeYellowCards")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Referee")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchStats", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchXgStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ActualHomeWin")
                        .HasColumnType("bit");

                    b.Property<int>("AwayShots")
                        .HasColumnType("int");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<double>("AwayXg")
                        .HasColumnType("float");

                    b.Property<int>("HomeShots")
                        .HasColumnType("int");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<double>("HomeXg")
                        .HasColumnType("float");

                    b.Property<bool>("HomeXgWin")
                        .HasColumnType("bit");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnderstatMatchId")
                        .HasColumnType("int");

                    b.Property<bool>("XgMatchedResult")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("UnderstatMatchId")
                        .IsUnique();

                    b.ToTable("MatchXgStats", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MlModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AlgorithmUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("CrossValidationMAE")
                        .HasColumnType("float");

                    b.Property<double>("CrossValidationStdDev")
                        .HasColumnType("float");

                    b.Property<string>("FeatureImportanceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HyperparametersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("MeanAbsoluteError")
                        .HasColumnType("float");

                    b.Property<double>("MeanAbsolutePercentageError")
                        .HasColumnType("float");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("RootMeanSquaredError")
                        .HasColumnType("float");

                    b.Property<double>("Rsquared")
                        .HasColumnType("float");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingDataRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrainingSamples")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("IX_MlModelVersions_Version");

                    b.HasIndex("ModelType", "IsActive")
                        .HasDatabaseName("IX_MlModelVersions_ModelType_IsActive");

                    b.ToTable("MlModelVersions", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.PlayerInjury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpectedReturn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InjuryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InjurySeverity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InjuryType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDoubtful")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKeyPlayer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "IsActive");

                    b.ToTable("PlayerInjuries", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.PlayerSuspension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpectedReturn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalPlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKeyPlayer")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SuspensionReason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "IsActive");

                    b.ToTable("PlayerSuspensions", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentMatchday")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StandingsLastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TeamsLastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WinnerTeamId");

                    b.HasIndex("CompetitionId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("CompetitionId", "IsCurrent");

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.SeasonTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("SeasonTeams", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClubColors")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tla")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamEloRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClubEloName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EloRank")
                        .HasColumnType("int");

                    b.Property<double>("EloRating")
                        .HasColumnType("float");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RatingDate");

                    b.HasIndex("TeamId", "RatingDate")
                        .IsUnique();

                    b.ToTable("TeamEloRatings", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamFormCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AwayGoalsConceded")
                        .HasColumnType("int");

                    b.Property<int>("AwayGoalsScored")
                        .HasColumnType("int");

                    b.Property<int>("AwayMatchesPlayed")
                        .HasColumnType("int");

                    b.Property<double>("AwayWinRate")
                        .HasColumnType("float");

                    b.Property<int>("AwayWins")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<double>("GoalsConcededPerMatch")
                        .HasColumnType("float");

                    b.Property<double>("GoalsPerMatch")
                        .HasColumnType("float");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("int");

                    b.Property<int>("HomeGoalsConceded")
                        .HasColumnType("int");

                    b.Property<int>("HomeGoalsScored")
                        .HasColumnType("int");

                    b.Property<int>("HomeMatchesPlayed")
                        .HasColumnType("int");

                    b.Property<double>("HomeWinRate")
                        .HasColumnType("float");

                    b.Property<int>("HomeWins")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastMatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesAnalyzed")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<double>("PointsPerMatch")
                        .HasColumnType("float");

                    b.Property<string>("RecentForm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedAt");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("TeamId", "CompetitionId")
                        .IsUnique();

                    b.ToTable("TeamFormCaches", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamInjuries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CaptainInjured")
                        .HasColumnType("bit");

                    b.Property<int>("Doubtful")
                        .HasColumnType("int");

                    b.Property<bool>("FirstChoiceGkInjured")
                        .HasColumnType("bit");

                    b.Property<string>("InjuredPlayerNames")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("InjuryImpactScore")
                        .HasColumnType("float");

                    b.Property<int>("KeyPlayersInjured")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongTermInjuries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextSyncDue")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShortTermInjuries")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TopScorerInjured")
                        .HasColumnType("bit");

                    b.Property<int>("TotalInjured")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamInjuries", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamInjurySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InjuredPlayerNames")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("InjuryImpactScore")
                        .HasColumnType("float");

                    b.Property<int>("KeyPlayersInjured")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalInjured")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "SnapshotDateUtc")
                        .IsUnique();

                    b.ToTable("TeamInjurySnapshots", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamSuspensions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CardSuspensions")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinarySuspensions")
                        .HasColumnType("int");

                    b.Property<int>("KeyPlayersSuspended")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextSyncDue")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspendedPlayerNames")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<double>("SuspensionImpactScore")
                        .HasColumnType("float");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalSuspended")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamSuspensions", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamUsualLineup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaptainName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MatchesAnalyzed")
                        .HasColumnType("int");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsualDefenders")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UsualFormation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsualForwards")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UsualGoalkeepers")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UsualMidfielders")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique();

                    b.ToTable("TeamUsualLineups", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamXgSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("RecentXgPerMatch")
                        .HasColumnType("float");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("date");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("XgAgainstPerMatch")
                        .HasColumnType("float");

                    b.Property<double>("XgOverperformance")
                        .HasColumnType("float");

                    b.Property<double>("XgPerMatch")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Season", "SnapshotDateUtc");

                    b.HasIndex("TeamId", "CompetitionId", "Season", "SnapshotDateUtc")
                        .IsUnique();

                    b.ToTable("TeamXgSnapshots", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamXgStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<int>("GoalsScored")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<double>("RecentXgAgainstPerMatch")
                        .HasColumnType("float");

                    b.Property<double>("RecentXgPerMatch")
                        .HasColumnType("float");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnderstatTeamId")
                        .HasColumnType("int");

                    b.Property<double>("XgAgainst")
                        .HasColumnType("float");

                    b.Property<double>("XgAgainstPerMatch")
                        .HasColumnType("float");

                    b.Property<double>("XgDiff")
                        .HasColumnType("float");

                    b.Property<double>("XgFor")
                        .HasColumnType("float");

                    b.Property<double>("XgOverperformance")
                        .HasColumnType("float");

                    b.Property<double>("XgPerMatch")
                        .HasColumnType("float");

                    b.Property<double>("XgaOverperformance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Season");

                    b.HasIndex("TeamId", "CompetitionId", "Season")
                        .IsUnique();

                    b.ToTable("TeamXgStats", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Bet", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.BetResult", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Bet", "Bet")
                        .WithOne("Result")
                        .HasForeignKey("ExtraTime.Domain.Entities.BetResult", "BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bet");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Bot", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.User", "User")
                        .WithOne("Bot")
                        .HasForeignKey("ExtraTime.Domain.Entities.Bot", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.BotPredictionAccuracy", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.CompetitionTeam", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany("CompetitionTeams")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany("CompetitionTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.FootballStanding", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany("FootballStandings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.HeadToHead", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team1")
                        .WithMany()
                        .HasForeignKey("Team1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team2")
                        .WithMany()
                        .HasForeignKey("Team2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.League", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.LeagueBotMember", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Bot", "Bot")
                        .WithMany()
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.League", "League")
                        .WithMany("BotMembers")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("League");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.LeagueMember", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.LeagueStanding", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Match", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchLineup", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Match", "Match")
                        .WithMany("Lineups")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchOdds", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Match", "Match")
                        .WithOne()
                        .HasForeignKey("ExtraTime.Domain.Entities.MatchOdds", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchStats", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Match", "Match")
                        .WithOne()
                        .HasForeignKey("ExtraTime.Domain.Entities.MatchStats", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.MatchXgStats", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.PlayerInjury", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.PlayerSuspension", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Season", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany("Seasons")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competition");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.SeasonTeam", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Season", "Season")
                        .WithMany("SeasonTeams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany("SeasonTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamEloRating", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamFormCache", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamInjuries", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithOne()
                        .HasForeignKey("ExtraTime.Domain.Entities.TeamInjuries", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamInjurySnapshot", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamSuspensions", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithOne()
                        .HasForeignKey("ExtraTime.Domain.Entities.TeamSuspensions", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamUsualLineup", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamXgSnapshot", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.TeamXgStats", b =>
                {
                    b.HasOne("ExtraTime.Domain.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtraTime.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Bet", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Competition", b =>
                {
                    b.Navigation("CompetitionTeams");

                    b.Navigation("Matches");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.League", b =>
                {
                    b.Navigation("BotMembers");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Match", b =>
                {
                    b.Navigation("Lineups");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Season", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("SeasonTeams");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("CompetitionTeams");

                    b.Navigation("FootballStandings");

                    b.Navigation("HomeMatches");

                    b.Navigation("SeasonTeams");
                });

            modelBuilder.Entity("ExtraTime.Domain.Entities.User", b =>
                {
                    b.Navigation("Bot");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
